AllCops:
  Includes:
    - Gemfile
    - metadata.rb
    - attributes/**
    - spec/**

  Excludes:
    - files/**
    - recipes/**
    - templates/**

# UTF-8 headers not generally in these files
Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

# ignore long lines
LineLength:
  Enabled: false

# ignore word arrays
WordArray:
  MinSize: 3
